# Generated by Django 6.0 on 2026-01-12 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_order_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='script_file',
            field=models.FileField(blank=True, null=True, upload_to='script_files/'),
        ),
    ]
