# Generated by Django 6.0 on 2026-01-12 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_product_script_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='slip_image',
            field=models.ImageField(blank=True, null=True, upload_to='payment_slips/', verbose_name='สลิปการชำระเงิน'),
        ),
    ]
