# Generated by Django 6.0 on 2026-01-14 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_sprint_remove_task_assignee_remove_task_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='source',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='From Sprint'),
        ),
    ]
